version: '3.3'
services:
  web:
    build: .
    container_name: php8-apache2
    volumes:
      - ./source:/var/www/html
      - ./config/vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/docker-web.ini:/usr/local/etc/php/conf.d//docker-php-ext-sodium.ini
    ports:
      - "80:80"
    links:
      - serverdb
  serverdb:
    image: mariadb:10.2
    container_name: serverdb
    restart: on-failure
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3306:3306