version: '3.3'
services:
  web:
    build: .
    container_name: php8-apache2
    volumes:
      - ./source:/var/www/html
    ports:
      - "80:80"
    links:
      - serverdb
  serverdb:
    image: mysql:5.7.37
    container_name: serverdb
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3306:3306